### ISSUE TITLE
Deprecate AtLeastOne arity

### ISSUE THREAD

**Issue by laughedelic** [bio4j/angulillos#52]
There are only three types of `outE`/`inE` methods, they return
- `E` for arity One
- `Optional<E>` for arity AtMostOne
- `Stream<E>` for arity Any (Many)

As there is no `NonEmptyStream<>` in Java, let's deprecate the `AtLeastOne` arity.

**Comment by eparejatobes** [comment]
I like it. It's useful as documentation, at the very least.

**Comment by laughedelic** [comment]
Mmmkay.. :neutral_face: If we were using some datatype to reflect this arity, I think it would be more useful. But ok. I'm closing this.
