### ISSUE TITLE
Restructure methods for adjacent edges/vertices

### ISSUE THREAD

**Issue by laughedelic** [bio4j/angulillos#53]
I have rough an idea on how to improve all these `inOneE`, `inOptionalE`, `inManyE`, etc. For that we'll need to make arities useful:

- split arity on two: in-arity and out-arity (there already are separate traits for this)
- add representation type to arity (`E`, `Optional<E>`, `Stream<E>`)
- put those arity specific in/out methods to the arity traits
- call them from the typed graph/vertex interfaces

Something like

```scala
    sealed trait Arity { 

      type C[E]
      def narrow(edges: Stream[E]): C[E]
    }

    trait ExactlyOne extends Arity { type C[E] = E; ... }
    trait AtMostOne  extends Arity { type C[E] = Option[E]; ... }
    trait ManyOrNone extends Arity { type C[E] = Stream[E]; ... }


    trait InArity extends Arity
    trait OutArity extends Arity

    trait FromExactlyOne extends InArity with ExactlyOne
    trait FromAtMostOne  extends InArity with AtMostOne
    trait FromManyOrNone extends InArity with ManyOrNone

    trait ToExactlyOne extends OutArity with ExactlyOne
    trait ToAtMostOne  extends OutArity with AtMostOne
    trait ToManyOrNone extends OutArity with ManyOrNone
```

then in the `TypedVertex`:

```java
  default <
    // src
    S extends TypedVertex<S,ST,SG,I,RV,RE>,
    ST extends TypedVertex.Type<S,ST,SG,I,RV,RE>,
    SG extends TypedGraph<SG,I,RV,RE>,
    // rel
    R extends TypedEdge<S,ST,SG, R,RT,RTA, RG,I,RV,RE, N,NT,G>,
    RT extends TypedEdge.Type<S,ST,SG, R,RT,RTA, RG,I,RV,RE, N,NT,G>,
    RTA extends TypedEdge.Type.Arity<...>,       // some magic here, please???
    RG extends TypedGraph<RG,I,RV,RE>
  >
  RTA<E> inE(RT relType) { return relType.arity.narrow(graph().inE(relType, self()); }
```

@eparejatobes WDYT?
Sorry for using scala here, but I think you got the idea. Do you think it's doable in Java?

**Comment by eparejatobes** [comment]
You cannot abstract over type constructors in Java. If something like that would be possible, then of course the whole library would be wildly different :smile:

**Comment by laughedelic** [comment]
![sad-crying-leonardo-dicaprio-14iZJ2agTAAb6w](https://camo.githubusercontent.com/476f7a6a496ab4a4623ad502c0d32681ab0dfe4d/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f3134695a4a3261675441416236772f67697068792e676966)
