### ISSUE TITLE
Split interfaces on read/write-only

### ISSUE THREAD

**Issue by laughedelic** [bio4j/angulillos#55]
I would split typed and untyped graph interfaces on parts with
- writing methods (`addVertex`/`addEdge`, `setProperty`, `commit`)
- reading methods (the rest)
- and probably indexes-related stuff

In the writing part we can add general methods for schema initialization. Then it's used for importing data.

The reading part is used for working with an instance of already imported data.

@eparejatobes WDYT?

**Comment by eparejatobes** [comment]
yes, fine.

**Comment by laughedelic** [comment]
It's not as easy as I expected and we decided to close it (and maybe return later)
